### ISSUE TITLE
Link to the demo in README.md is incorrect

### ISSUE THREAD

**Issue by dblume** [skmalve/Circle-Digitizer#2]
Hi Sai!

Here's any easy one to fix. The line in README.md that says:
`[Click here to check out the demo!](https://skmalve.github.io/Circle-Digitizer/)`
should point to the actual page at `https://saikumarmalve.github.io/Circle-Digitizer/`.

**Comment by SaiKumarMalve** [comment]
Thanks for noting that, David. I changed the username recently. I have updated the URL now.
